apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-prometheus-sec
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-contour
  interval: 5m0s
  path: ./03-packages/prometheus-psp
  prune: true
  sourceRef:
    kind: GitRepository
    name: livefire-tmc
    namespace: tanzu-continuousdelivery-resources
