apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tanzu-system-envoy-restricted
spec:
  allowPrivilegeEscalation: false
  hostPorts:
  - min: 80
    max: 80
  - min: 443
    max: 443
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
