---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-namespaces
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 5m0s
  path: ./continuous-delivery/opa/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: livefire-tmc
    namespace: tanzu-continuousdelivery-resources


