---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-cert-manager
  namespace: tanzu-continuousdelivery-resources
spec:
  #dependsOn:
    #- name: packages-ns-sa.yaml
  interval: 5m0s
  path: ./03-packages/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: livefire-tmc
    namespace: tanzu-continuousdelivery-resources
