apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-packages
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-packages-sa
  namespace: tanzu-packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-packages-role
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclass
  verbs:
  - "list"
  - "use"
  - "get"
- apiGroups:
  - ""
  resources:
  - persistenvolumeclaim
  - peristenvolume
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - "*"
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs: 
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - use
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - use
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - vmware-system-privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-packages-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-packages-role
subjects:
- kind: ServiceAccount
  name: tanzu-packages-sa
  namespace: tanzu-packages
